
server:
  port: 8080


extraEnvHost: 212.64.18.166


app:
  id: shardingJDBC
apollo:
  meta: http://${extraEnvHost}:8080
  bootstrap:
    namespaces: application,common-mysql
    enabled: true
    eagerLoad:
      enabled: false


spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${extraEnvHost}:3306/sharding?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&rewriteBatchedStatements=true
        username: ${jdbc.username}
        password: ${jdbc.pwd}
    sharding:
      tables:
        user:
          actual-data-nodes: ds0.user_20211${0..2},ds0.user_20210${1..9}
          table-strategy:
            standard:
              sharding-column: s_id
              preciseAlgorithmClassName: com.robben.sharding.utils.PreciseTableShardingAlgorithm
              rangeAlgorithmClassName: com.robben.sharding.utils.RangeTableShardingAlgorithm
          key-generator:
            column: id
            type: SNOWFLAKE
    props:
      sql:
        show: true


#MyBatis-Plus的相关配置
mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO







