
#springboot2.4之后,配置文件的加载发生改变。需要手动引入spring-cloud-starter-bootstrap的jar包 https://blog.csdn.net/weixin_43272781/article/details/116718747

server:
  port: 28083

serverHost: 212.64.18.166


spring:
  application:
    name: sentinelDemo
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: ${serverHost}:8080



