


#设置项目名
server:
  port: 28083

nacosServerHost: 212.64.18.166


spring:
  application:
    name: nacos-discovery-config
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      config:
        server-addr: ${nacosServerHost}:30000
        file-extension: properties
      discovery:
        server-addr: ${nacosServerHost}:30000

#        #注意:配置group的时候,必须配置一个namespace(这个值是从nacos控制台命名空间获取的ID值),这样才能设置权重和负载均衡
#        namespace: rrrrrrrrr
#        cluster-name: kkk

